### ISSUE TITLE
Error while migrating to Angular 11

### ISSUE THREAD

**Issue by andRave** [dotcore64/i18next-fetch-backend#58]
![image](https://user-images.githubusercontent.com/15156046/139576002-ca815ce9-51e2-4ff0-a65f-fd2a0bf90a3a.png)
![image](https://user-images.githubusercontent.com/15156046/139576012-96cf09a9-76ab-4f2a-b5b4-77d5e3cb2a45.png)

Hi, I got this error while migrating to Angular 11. Unfortunately, I can't figure out how to fix it. 4.0.0 version. Also on the 3rd and 2nd versions.

**Comment by perrin4869** [comment]
Hm... This doesn't sound related to Angular, but rather a typescript type issue. I looked at the types declaration file, and `ReadCallback` is pulled right out of `i18next`... so I would guess that you have two incompatible versions of `i18next` installed? You could confirm this by doing `npm ls i18next`

**Comment by andRave** [comment]
![image](https://user-images.githubusercontent.com/15156046/139579634-9cada75c-e881-404d-bbba-d4137a74cd1d.png)

Yeah, sounds reasonable, but here is my list. Looks like everything is legit.

Also angular-i18next seems compatible with i18next:
![image](https://user-images.githubusercontent.com/15156046/139580531-ee584c7a-7bff-45ec-b5bd-afe75cafb1e5.png)

**Comment by perrin4869** [comment]
Ah, I see, the culprit seems to be this commit: https://github.com/i18next/i18next/commit/9d77723e5b16079680bf6b7c3a42b4d88a253666

Seems like an easy fix!
The thing is, `i18next` is only a `dev` and `typescript` dependency, so I am not sure how to enforce this change...

**Comment by perrin4869** [comment]
Can you try `4.1.0`? If you got any ideas how to automate and improve on the typescript type checking, I'll be happy to take in a PR :)

**Comment by andRave** [comment]
Perfecto, thanks a lot) I don't think that there is a possibility to automatically update or get types from source, but maybe it's just I don`t know how to do it. Need to investigate this question ^_^

**Comment by perrin4869** [comment]
Yeah, thanks for catching this issue!
Well it'd be nice if there was some way to enforce versions only when using the typescript types... because adding `i18next` as a `peerDependency` here doesn't feel right, since it's only a type dependency...
Closed in f0f28fc8e0fc5c93259abfaf8e74eaee1998d782

**Comment by andRave** [comment]
Yes, but could i18next-fetch-backend be used without i18next?) Nope, the user will install i18next anyway.

**Comment by perrin4869** [comment]
Yeah, that's the upside, maybe the pragmatic thing to do...
But still doesn't feel right...
